language: python

install:
  - pip install pytest-pylint
  - pip install pytest-flake8

jobs:
  include:
    - stage: lint
      script: pytest --flake8
    - script: pytest --pylint
    - stage: test
      script: python3 autoLyrics.py
      
stages:
  - lint
  - test
