language: python

jobs:
  include:
    - stage: lint
      install: pip install pytest-flake8
      script: pytest --flake8
    - install: pip install pytest-pylint
      script: pytest --pylint
    - install: sudo apt install inkscape
      stage: test
      script: python3 auto_lyrics.py

stages:
  - lint
  - test
